### ISSUE TITLE
Authentication Panel

### ISSUE THREAD

**Issue by doxylgits** [doublejai/CMSC495_Project#21]

**Comment by doxylgits** [comment]
The authentication panel is the login panel in the main window. Please let me know if a new panel needs to be created.

**Comment by mvpwizard** [comment]
If you change the login panel to use the authentication subsystem then we don't need an authentication panel.

**Comment by doxylgits** [comment]
The login panel doesn't exist with the current rewrite of the main panel. I'm going to work on including the authentication interface into the authentication panel and create a new pull request.
